repos:
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['-i', '--remove-all-unused-imports']
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
  -   repo: https://github.com/asottile/reorder-python-imports
      rev: v3.10.0
      hooks:
      -   id: reorder-python-imports
